from typing import Protocol, Optional
from app.models.user import User

class UsersRepositoryInterface(Protocol):
    def getUserByUsername(self, username) -> Optional[User]:...
    def insertUser(self, user: User) -> None:...
    def existsUsername(self, username: str) -> bool:...

